// <auto-generated />
using System;
using MealPlanner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealPlanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MealPlannerDbContext))]
    partial class MealPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MealPlanner.Domain.Inventory.DefaultProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountPerPackage")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DefaultShelfLifeDays")
                        .HasColumnType("int");

                    b.Property<string>("DefaultLocationCanonical")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DefaultLocationDisplay")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<int>("MeasurementTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementTypeId");

                    b.HasIndex("UserId", "Id");

                    b.HasIndex("UserId", "Name", "IsCurrent");

                    b.ToTable("default_product", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Inventory.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("date");

                    b.Property<Guid>("DefaultProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LocationCanonical")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LocationDisplay")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("RemainingAmountMetric")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateOnly>("SellByDate")
                        .HasColumnType("date");

                    b.Property<decimal>("SnapshotAmountPerPackage")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("SnapshotMeasurementTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultProductId");

                    b.HasIndex("SnapshotMeasurementTypeId");

                    b.HasIndex("UserId", "DefaultProductId");

                    b.HasIndex("UserId", "LocationCanonical");

                    b.ToTable("inventory_item", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Inventory.MeasurementType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("measurement_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "g",
                            Name = "Grams"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ml",
                            Name = "Milliliters"
                        },
                        new
                        {
                            Id = 3,
                            Code = "piece",
                            Name = "Piece"
                        });
                });

            modelBuilder.Entity("MealPlanner.Domain.Meals.MealDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("meal_definition", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Meals.MealIngredientLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DefaultProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IngredientKind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MealDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MeasurementTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UnknownIngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultProductId");

                    b.HasIndex("MealDefinitionId");

                    b.HasIndex("MeasurementTypeId");

                    b.HasIndex("UnknownIngredientId");

                    b.HasIndex("UserId", "MealDefinitionId", "SortOrder");

                    b.ToTable("meal_ingredient_line", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Meals.UnknownIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConvertedDefaultProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("MeasurementTypeId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ConvertedDefaultProductId");

                    b.HasIndex("MeasurementTypeId");

                    b.HasIndex("UserId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("unknown_ingredient", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Inventory.DefaultProduct", b =>
                {
                    b.HasOne("MealPlanner.Domain.Inventory.MeasurementType", null)
                        .WithMany()
                        .HasForeignKey("MeasurementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MealPlanner.Domain.Inventory.InventoryItem", b =>
                {
                    b.HasOne("MealPlanner.Domain.Inventory.DefaultProduct", null)
                        .WithMany()
                        .HasForeignKey("DefaultProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPlanner.Domain.Inventory.MeasurementType", null)
                        .WithMany()
                        .HasForeignKey("SnapshotMeasurementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MealPlanner.Domain.Meals.MealIngredientLine", b =>
                {
                    b.HasOne("MealPlanner.Domain.Inventory.DefaultProduct", null)
                        .WithMany()
                        .HasForeignKey("DefaultProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealPlanner.Domain.Meals.MealDefinition", null)
                        .WithMany("IngredientLines")
                        .HasForeignKey("MealDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Domain.Inventory.MeasurementType", null)
                        .WithMany()
                        .HasForeignKey("MeasurementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPlanner.Domain.Meals.UnknownIngredient", null)
                        .WithMany()
                        .HasForeignKey("UnknownIngredientId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MealPlanner.Domain.Meals.UnknownIngredient", b =>
                {
                    b.HasOne("MealPlanner.Domain.Inventory.DefaultProduct", null)
                        .WithMany()
                        .HasForeignKey("ConvertedDefaultProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealPlanner.Domain.Inventory.MeasurementType", null)
                        .WithMany()
                        .HasForeignKey("MeasurementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MealPlanner.Domain.Meals.MealDefinition", b =>
                {
                    b.Navigation("IngredientLines");
                });
#pragma warning restore 612, 618
        }
    }
}
